package com.project.issue_replayer.entity;

import java.time.LocalDateTime;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Stores details of every failed API request so we can
 * investigate, analyze, and replay them later.
 */
@Entity
@Table(name = "failed_api_request")
@Data                // Generates getters, setters, toString, equals, hashCode
@NoArgsConstructor   // JPA needs an empty constructor
@AllArgsConstructor  // Constructor with all fields (useful for testing)
@Builder             // Lets you create objects like: FailedApiRequest.builder().endpoint("/api/users").build()
public class FailedApiRequest {

    /**
     * Unique ID - auto-generated by the database.
     * You never set this manually.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * HTTP method: GET, POST, PUT, DELETE, PATCH
     * Needed to replay the exact same type of request.
     */
    @Column(nullable = false, length = 10)
    private String httpMethod;

    /**
     * The API endpoint that failed.
     * Example: "/api/users/123" or "/api/orders"
     */
    @Column(nullable = false, length = 500)
    private String endpoint;

    /**
     * The JSON request body that was sent.
     * Stored as TEXT because it can be large.
     * Can be null (e.g., GET requests have no body).
     */
    @Column(columnDefinition = "TEXT")
    private String requestBody;

    /**
     * HTTP status code returned.
     * Examples: 400 (Bad Request), 500 (Server Error), 503 (Service Unavailable)
     */
    @Column(nullable = false)
    private int statusCode;

    /**
     * The error message or response body from the failed request.
     * Stored as TEXT because error messages can be long (stack traces, etc).
     */
    @Column(columnDefinition = "TEXT")
    private String errorMessage;

    /**
     * When the failure happened.
     * Automatically set to "now" if not provided.
     */
    @Column(nullable = false)
    private LocalDateTime timestamp;

    /**
     * Has this failed request been replayed/retried?
     * false = not yet replayed, true = already replayed
     */
    @Column(nullable = false)
    @Builder.Default
    private boolean replayed = false;

    /**
     * How many times this request has been replayed.
     * Used to prevent infinite retries. Default = 0.
     */
    @Column(nullable = false)
    @Builder.Default
    private int replayCount = 0;
}
